version: '3.4'

services:
  sql.data:
    image: microsoft/mssql-server-linux:latest
    container_name: sql.data
    environment:
      ACCEPT_EULA: 'Y' 
      SA_PASSWORD: 'TestePratico123'
    ports:
        - "5433:1433"
    volumes:
      - sqldata:/var/opt/mssql
    networks: 
        - isolated_network

  testepratico.api:
    image: ${DOCKER_REGISTRY}testepraticoapi
    build:
      context: .
      dockerfile: TestePratico.Api/Dockerfile
    environment:
      CONNECTION_STRING: "Server=sql.data;Database=TestePratico;User Id=sa;Password=TestePratico123"
    depends_on:
      - sql.data
    ports:
      - "9090:80"
    networks: 
        - isolated_network


volumes:
  sqldata:


networks:
  isolated_network: